from enum import Enum


class UploadError(Enum):
    DOCUMENT_NAME_DUPLICATED = "DOCUMENT_NAME_DUPLICATED"
    DOCUMENT_NAME_IN_DB = "DOCUMENT_NAME_IN_DB"
    INVALID_FILE_TYPE = "INVALID_FILE_TYPE"
    SCHEMA_VALIDATION_ERROR = "SCHEMA_VALIDATION_ERROR"
