repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: detect-private-key


  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.1.2
    hooks:
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: 'v2.3.2'
    hooks:
      - id: prettier
        files: holy-grail-frontend/src/.*\.(js|jsx|ts|tsx)$
        args: [ '--write', '--config', './holy-grail-frontend/.prettierrc' ]
