x-logging: &default-logging
  driver: loki
  options:
    loki-url: 'http://localhost:3100/api/prom/push'
    loki-pipeline-stages: |
      - multiline:
          firstline: '^\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2}'
          max_wait_time: 3s
      - regex:
          expression: '^(?P<time>\d{4}-\d{2}-\d{2} \d{1,2}:\d{2}:\d{2},d{3}) (?P<message>(?s:.*))$$'
      

version: '3.8'

services:
  holy-grail-backend:
    container_name: holy-grail-backend
    build: ./holy-grail-backend/backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
      - "9000:9000"
    networks:
      - holy-grail-network
    depends_on:
      - holy-grail-db
      - holy-grail-scheduler
      - loki
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_CONTAINER_URL: ${FRONTEND_CONTAINER_URL}
      BACKEND_CONTAINER_URL: ${BACKEND_CONTAINER_URL}
      GOOGLE_APPLICATION_PROPERTY_ID: ${GOOGLE_APPLICATION_PROPERTY_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      CELERY_BROKER_URL: ${REDIS_URL}
      CELERY_RESULT_BACKEND: ${REDIS_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DATABASE_URL: ${DATABASE_URL}
      TASK_RUNNER_DATABASE_URL: ${TASK_RUNNER_DATABASE_URL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      SECRET_KEY: ${SECRET_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_CLOUDFRONT_URL: ${AWS_CLOUDFRONT_URL}
      MAILTRAP_BEARER_TOKEN: ${MAILTRAP_BEARER_TOKEN}
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
      API_KEY: ${API_KEY}
      PRODUCTION: ${PRODUCTION}
    logging: *default-logging
    restart: unless-stopped
    volumes:
      - ./holy-grail-backend/backend:/app
      - ./holy-grail-402514-f862e946664e.json:/app/holy-grail-402514-f862e946664e.json

  holy-grail-db:
    container_name: holy-grail-db
    networks:
      - holy-grail-network
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
    image: postgres:14.1-alpine
    ports:
      - '5434:5432'
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
      - ./holy-grail-backend/db:/docker-entrypoint-initdb.d/

  holy-grail-redis:
    image: redis:7.0.7-alpine
    networks:
      - holy-grail-network
    ports:
      - "6379"
    depends_on:
      - holy-grail-db
    command: redis-server --loglevel verbose
    restart: unless-stopped

  holy-grail-scheduler:
    networks:
      - holy-grail-network
    environment:
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_URL: ${BACKEND_URL}
      FRONTEND_CONTAINER_URL: ${FRONTEND_CONTAINER_URL}
      BACKEND_CONTAINER_URL: ${BACKEND_CONTAINER_URL}
      GOOGLE_APPLICATION_PROPERTY_ID: ${GOOGLE_APPLICATION_PROPERTY_ID}
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
      CELERY_BROKER_URL: ${REDIS_URL}
      CELERY_RESULT_BACKEND: ${REDIS_URL}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      DATABASE_URL: ${DATABASE_URL}
      TASK_RUNNER_DATABASE_URL: ${TASK_RUNNER_DATABASE_URL}
      ACCESS_TOKEN_EXPIRE_MINUTES: ${ACCESS_TOKEN_EXPIRE_MINUTES}
      ALGORITHM: ${ALGORITHM}
      SECRET_KEY: ${SECRET_KEY}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
      AWS_S3_ACCESS_KEY_ID: ${AWS_S3_ACCESS_KEY_ID}
      AWS_S3_SECRET_ACCESS_KEY: ${AWS_S3_SECRET_ACCESS_KEY}
      AWS_CLOUDFRONT_URL: ${AWS_CLOUDFRONT_URL}
      MAILTRAP_BEARER_TOKEN: ${MAILTRAP_BEARER_TOKEN}
      MAILTRAP_API_KEY: ${MAILTRAP_API_KEY}
    depends_on:
      - holy-grail-redis
    build:
      context: ./holy-grail-backend/backend
    command: celery -A app.utils.worker worker -B --loglevel=info
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "celery inspect ping" ]
    volumes:
      - ./holy-grail-backend/backend:/app
      - ./holy-grail-402514-f862e946664e.json:/app/holy-grail-402514-f862e946664e.json

  holy-grail-scheduler-gui:
    networks:
      - holy-grail-network
    environment:
      CELERY_BROKER_URL: ${REDIS_URL}
    links:
      - holy-grail-scheduler
    ports:
      - "5555:5555"
    depends_on:
      holy-grail-scheduler:
        condition: service_healthy
    image: mher/flower:1.2.0
    restart: unless-stopped

  loki:
    networks:
      - holy-grail-network
    image: grafana/loki:2.9.3
    command: -config.file=/etc/loki/local-config.yaml
    ports:
      - "3100:3100"
    volumes:
      - loki_data:/loki
    restart: unless-stopped


  prometheus:
    networks:
      - holy-grail-network
    image: prom/prometheus:v2.48.1
    ports:
      - "9090:9090"
    volumes:
      - ./holy-grail-backend/etc/prometheus:/workspace
      - prometheus_data:/prometheus
    command:
      - --config.file=/workspace/prometheus.yml
      - --enable-feature=exemplar-storage
    depends_on:
      - loki
    logging: *default-logging
    restart: unless-stopped


  tempo:
    networks:
      - holy-grail-network
    image: grafana/tempo:2.3.1
    command: [ "--target=all", "--storage.trace.backend=local", "--storage.trace.local.path=/var/tempo", "--auth.enabled=false" ]
    ports:
      - "4317:4317"
      - "4318:4318"
    depends_on:
      - loki
    logging: *default-logging
    restart: unless-stopped

  grafana:
    networks:
      - holy-grail-network
    image: grafana/grafana:10.2.3
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: ${GF_SECURITY_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - ./holy-grail-backend/etc/grafana/:/etc/grafana/provisioning/datasources
      - ./holy-grail-backend/etc/dashboards.yaml:/etc/grafana/provisioning/dashboards/dashboards.yaml
      - ./holy-grail-backend/etc/dashboards:/etc/grafana/dashboards
    depends_on:
      - loki
      - prometheus
    logging: *default-logging
    restart: unless-stopped

volumes:
  prometheus_data: {}
  loki_data: {}


networks:
  holy-grail-network:
    name: holy-grail-network
    driver: bridge
