FROM oven/bun:1.2.8-slim AS base

FROM base AS builder
WORKDIR /app

COPY package.json bun.lockb ./

RUN bun install --frozen-lockfile

COPY . .

ENV NODE_ENV=development

RUN bun run build-dev

FROM oven/bun:1.2.8-slim AS runner
WORKDIR /app

COPY --from=builder /app ./

EXPOSE 3000

CMD ["bun", "run", "start"]