"""email-update

Revision ID: 23721ba0e461
Revises: bb91390b0ea8
Create Date: 2023-06-08 13:27:47.810468

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23721ba0e461'
down_revision = 'bb91390b0ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('verified', sa.Boolean(), server_default='f', nullable=False))
    op.add_column('account', sa.Column('email_verification_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'email_verification_token')
    op.drop_column('account', 'verified')
    # ### end Alembic commands ###
