"""add-extension-to-notes

Revision ID: 2a01135883a9
Revises: ab2ee1df8d7b
Create Date: 2023-10-13 08:05:06.661645

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "2a01135883a9"
down_revision = "ab2ee1df8d7b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Add the 'extension' column without setting a default
    op.add_column("library", sa.Column("extension", sa.String()))

    # Step 2: Update the extension column based on file_name values
    op.execute("UPDATE library SET extension = '.pdf' WHERE file_name LIKE '%.pdf'")
    op.execute("UPDATE library SET extension = '.zip' WHERE file_name LIKE '%.zip'")

    # Update the 'document_name' column to remove the .pdf and .zip extensions
    op.execute(
        "UPDATE library SET document_name = SUBSTRING(document_name, 1, LENGTH(document_name) - 4) WHERE document_name "
        "LIKE "
        "'%.pdf' "
        "OR file_name LIKE '%.zip'"
    )

    # Step 3: Set the extension column to NOT NULL
    op.alter_column("library", "extension", nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "UPDATE library SET document_name = CONCAT(document_name, '.pdf') WHERE extension = 'pdf'"
    )
    op.execute(
        "UPDATE library SET document_name = CONCAT(document_name, '.zip') WHERE extension = 'zip'"
    )
    op.drop_column("library", "extension")
    # ### end Alembic commands ###
