"""add-year-attribute

Revision ID: 302ae8bd6669
Revises: d81d1a680b0d
Create Date: 2023-08-05 10:22:07.116553

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision = "302ae8bd6669"
down_revision = "d81d1a680b0d"
branch_labels = None
depends_on = None


def populate_year():
    connection = op.get_bind()

    for year in range(2008, 2024):
        query = text(
            """
            UPDATE library
            SET year = :year
            WHERE document_name LIKE :year_pattern
        """
        )
        connection.execute(query, {"year": year, "year_pattern": f"%{year}%"})


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("library", sa.Column("year", sa.Integer(), nullable=True))
    op.create_index(op.f("ix_library_approved"), "library", ["approved"], unique=False)
    op.create_index(op.f("ix_library_year"), "library", ["year"], unique=False)
    # ### end Alembic commands ###

    populate_year()


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_library_year"), table_name="library")
    op.drop_index(op.f("ix_library_approved"), table_name="library")
    op.drop_column("library", "year")
    # ### end Alembic commands ###
