"""add-analytics-2

Revision ID: 371e18330e69
Revises: c10697d78678
Create Date: 2023-10-21 11:05:08.380731

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "371e18330e69"
down_revision = "c10697d78678"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analytics",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("file_download_count", sa.Integer(), nullable=False),
        sa.Column("unique_active_users", sa.Integer(), nullable=False),
        sa.Column("user_count", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_analytics_id"), "analytics", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analytics_id"), table_name="analytics")
    op.drop_table("analytics")
    # ### end Alembic commands ###
