"""add-approval

Revision ID: 56932aefadce
Revises: 18e926ce4270
Create Date: 2023-05-16 14:50:29.060939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "56932aefadce"
down_revision = "18e926ce4270"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "library",
        sa.Column("approved", sa.Boolean(), server_default="f", nullable=False),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("library", "approved")
    # ### end Alembic commands ###
