"""add-reset-password

Revision ID: 5797ef4920d2
Revises: 23721ba0e461
Create Date: 2023-06-09 06:31:25.919949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5797ef4920d2"
down_revision = "23721ba0e461"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account", sa.Column("reset_password_token", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("account", "reset_password_token")
    # ### end Alembic commands ###
