"""update

Revision ID: 8fda183cf6e8
Revises: e8da151c2972
Create Date: 2023-05-31 10:01:24.090947

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fda183cf6e8'
down_revision = 'e8da151c2972'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('library', sa.Column('document_name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('library', 'document_name')
    # ### end Alembic commands ###
