"""update-unique

Revision ID: bb91390b0ea8
Revises: 8fda183cf6e8
Create Date: 2023-06-02 10:27:38.482895

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "bb91390b0ea8"
down_revision = "8fda183cf6e8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category_level", ["name"])
    op.create_unique_constraint(None, "documents", ["name"])
    op.create_unique_constraint(None, "library", ["document_name"])
    op.create_unique_constraint(None, "subjects", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="unique")
    op.drop_constraint(None, "library", type_="unique")
    op.drop_constraint(None, "documents", type_="unique")
    op.drop_constraint(None, "category_level", type_="unique")
    # ### end Alembic commands ###
