"""add-analytics

Revision ID: c10697d78678
Revises: 2a01135883a9
Create Date: 2023-10-21 10:43:21.922842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c10697d78678"
down_revision = "2a01135883a9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
