"""add-ad-analytics

Revision ID: c9477830b12f
Revises: d710d2405b9f
Create Date: 2023-11-23 13:12:48.394393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "c9477830b12f"
down_revision = "d710d2405b9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_analytics",
        sa.Column(
            "timestamp",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("timestamp"),
    )
    op.create_index(
        op.f("ix_ad_analytics_timestamp"), "ad_analytics", ["timestamp"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ad_analytics_timestamp"), table_name="ad_analytics")
    op.drop_table("ad_analytics")
    # ### end Alembic commands ###
