"""unique-subject-name-combination

Revision ID: cdbba4736a34
Revises: ef9811ae2269
Create Date: 2023-07-09 12:04:17.171585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cdbba4736a34"
down_revision = "ef9811ae2269"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "category_level_name_unique", "subjects", ["name", "category_id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("category_level_name_unique", "subjects", type_="unique")
    # ### end Alembic commands ###
