"""add-ad-analytics

Revision ID: d30ae94f4500
Revises: d710d2405b9f
Create Date: 2023-11-28 10:40:31.915704

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d30ae94f4500"
down_revision = "d710d2405b9f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_analytics",
        sa.Column("date", sa.Date(), server_default=sa.text("now()"), nullable=False),
        sa.Column("views", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("date"),
    )
    op.create_index(
        op.f("ix_ad_analytics_date"), "ad_analytics", ["date"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ad_analytics_date"), table_name="ad_analytics")
    op.drop_table("ad_analytics")
    # ### end Alembic commands ###
