"""remove-unique-subject-name

Revision ID: ef9811ae2269
Revises: f43e324b8b8d
Create Date: 2023-07-09 12:00:18.858345

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ef9811ae2269"
down_revision = "f43e324b8b8d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("subjects_name_key", "subjects", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("subjects_name_key", "subjects", ["name"])
    # ### end Alembic commands ###
