"""subject-education-level-relationship

Revision ID: f43e324b8b8d
Revises: 5797ef4920d2
Create Date: 2023-07-09 11:57:38.710767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "f43e324b8b8d"
down_revision = "5797ef4920d2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("category_level_name_key", "category_level", type_="unique")
    op.add_column("subjects", sa.Column("category_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "subjects", "category_level", ["category_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "subjects", type_="foreignkey")
    op.drop_column("subjects", "category_id")
    op.create_unique_constraint("category_level_name_key", "category_level", ["name"])
    # ### end Alembic commands ###
