"""remove-unique-doc-name

Revision ID: ab2ee1df8d7b
Revises: 302ae8bd6669
Create Date: 2023-08-25 18:42:50.328957

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ab2ee1df8d7b"
down_revision = "302ae8bd6669"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_library_document_name", table_name="library")
    op.create_index(
        op.f("ix_library_document_name"), "library", ["document_name"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_library_document_name"), table_name="library")
    op.create_index(
        "ix_library_document_name", "library", ["document_name"], unique=False
    )
    # ### end Alembic commands ###
