"""fix-analytics-default-timestamp

Revision ID: bffa95ea4989
Revises: 371e18330e69
Create Date: 2023-10-27 06:55:59.687793

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.sql import text

# revision identifiers, used by Alembic.
revision = "bffa95ea4989"
down_revision = "371e18330e69"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add new column with server default
    op.add_column(
        "analytics",
        sa.Column(
            "new_timestamp", sa.DateTime, server_default=text("now()"), nullable=False
        ),
    )

    # Copy data from old column to new column
    op.execute("UPDATE analytics SET new_timestamp = timestamp")

    # Drop old column
    op.drop_column("analytics", "timestamp")

    # Rename new column
    op.alter_column("analytics", "new_timestamp", new_column_name="timestamp")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the old column back without server default
    op.add_column("analytics", sa.Column("timestamp", sa.DateTime, nullable=False))

    # Copy data from new column back to old column
    op.execute("UPDATE analytics SET timestamp = new_timestamp")

    # Drop new column
    op.drop_column("analytics", "new_timestamp")


# ### end Alembic commands ###
