services:
  db:
    container_name: db
    env_file:
      - ../../apps/backend/.env
    healthcheck:
      interval: 5s
      retries: 10
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB" ]
    image: postgres:14.1-alpine
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-app}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

  db-migrate:
    container_name: db-migrate
    image: python:3.11-slim
    env_file:
      - ../../apps/backend/.env
    environment:
      POSTGRES_HOST: db
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ../../apps/backend:/app
    working_dir: /app
    command: >
      sh -c "
        pip install alembic psycopg2-binary sqlalchemy pydantic pydantic-settings pytz asyncpg &&
        alembic upgrade head &&
        echo 'Migrations completed successfully'
      "
    restart: "no"

  redis:
    container_name: redis
    image: redis:7.0.7-alpine
    ports:
      - "6379:6379"
    depends_on:
      - db
    command: redis-server --loglevel verbose
    restart: unless-stopped

#  celery:
#    container_name: celery
#    networks:
#      - holy-grail-network
#    env_file:
#      - ../../apps/backend/.env
#    depends_on:
#      - redis
#    build:
#      context: ../../apps/backend
#    command: celery -A app.utils.worker worker -B --loglevel=info
#    restart: unless-stopped
#    healthcheck:
#      test: [ "CMD-SHELL", "celery inspect ping" ]
#    volumes:
#      - ../../docker-volumes/backend:/app

volumes:
  postgres_data: