"""Rename Starred_files to favourite_files

Revision ID: 2cecad328730
Revises: 95aad19d1ae6
Create Date: 2025-12-04 21:35:04.323549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cecad328730'
down_revision = '95aad19d1ae6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('favourite_files', sa.String(), nullable=True))
    op.drop_column('account', 'starred_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('starred_files', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('account', 'favourite_files')
    # ### end Alembic commands ###
