"""Moved Favourites to its own table

Revision ID: 73246e7e5e36
Revises: 8092c031dfc1
Create Date: 2025-12-05 12:26:40.389247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73246e7e5e36'
down_revision = '8092c031dfc1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Create the `user_favourites` table and associated indexes and foreign key constraints.
    
    Creates a table named `user_favourites` with columns:
    - `id` (primary key)
    - `user_id` (references `account.user_id`)
    - `file_id` (references `library.id`)
    
    Also creates non-unique indexes on `id`, `user_id`, and `file_id`.
    """
    op.create_table('user_favourites',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['library.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['account.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_favourites_file_id'), 'user_favourites', ['file_id'], unique=False)
    op.create_index(op.f('ix_user_favourites_id'), 'user_favourites', ['id'], unique=False)
    op.create_index(op.f('ix_user_favourites_user_id'), 'user_favourites', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Reverses the migration by removing the user_favourites table and its associated indexes.
    
    Drops the indexes `ix_user_favourites_user_id`, `ix_user_favourites_id`, and `ix_user_favourites_file_id` on the `user_favourites` table, then drops the `user_favourites` table itself.
    """
    op.drop_index(op.f('ix_user_favourites_user_id'), table_name='user_favourites')
    op.drop_index(op.f('ix_user_favourites_id'), table_name='user_favourites')
    op.drop_index(op.f('ix_user_favourites_file_id'), table_name='user_favourites')
    op.drop_table('user_favourites')
    # ### end Alembic commands ###