"""Moved Favourites to its own table

Revision ID: 8092c031dfc1
Revises: 2cecad328730
Create Date: 2025-12-05 12:22:55.503494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8092c031dfc1'
down_revision = '2cecad328730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Apply the migration that removes the `favourite_files` column from the `account` table.
    
    This migration moves favourites to a dedicated table by dropping the `favourite_files` column from the `account` table.
    """
    op.drop_column('account', 'favourite_files')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    """
    Restore the `favourite_files` column on the `account` table.
    
    Adds a nullable VARCHAR column named `favourite_files` to the `account` table to reverse the migration that dropped it.
    """
    op.add_column('account', sa.Column('favourite_files', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###