"""Added Starred Files Column to Auth Table

Revision ID: 95aad19d1ae6
Revises: 4b5888d54fc3
Create Date: 2025-12-04 12:35:18.549780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95aad19d1ae6'
down_revision = '4b5888d54fc3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('starred_files', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('account', 'starred_files')
    # ### end Alembic commands ###
