"""unique-category

Revision ID: d81d1a680b0d
Revises: 687b59af50ab
Create Date: 2023-07-31 06:35:55.571761

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d81d1a680b0d"
down_revision = "687b59af50ab"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "category_level", ["name"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "category_level", type_="unique")
    # ### end Alembic commands ###
