import type { Metadata } from "next";
import "./globals.css";
import { ClientProvider } from "@shared/ui/providers";
import { twMerge } from "tailwind-merge";
import { Plus_Jakarta_Sans, Patrick_Hand_SC } from "next/font/google";
import { Header, Footer } from "@/lib/features/server";
import { Toaster } from "react-hot-toast";
import type { ReactNode } from "react";

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	style: ["normal", "italic"],
	variable: "--font-plus-jakarta",
	display: "swap",
});

const patrickHand = Patrick_Hand_SC({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-patrick-hand",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={twMerge(
					"min-h-screen dark:bg-zinc-800 bg-zinc-100 transition-all",
					plusJakarta.variable,
					patrickHand.variable,
				)}
			>
				<ClientProvider>
					<Header />
					{children}
					<Footer />
					<Toaster
						position="bottom-right"
						toastOptions={{
							className: "!bg-zinc-100 !text-zinc-900 dark:!bg-zinc-900 dark:!text-white",
						}}
					/>
				</ClientProvider>
			</body>
		</html>
	);
}
