import type { Metadata } from "next";
import "./globals.css";
import { ClientProvider } from "@shared/ui/providers";
import { twMerge } from "tailwind-merge";
import { Plus_Jakarta_Sans, Patrick_Hand_SC } from "next/font/google";
import { Header } from "@lib/features";

const plusJakarta = Plus_Jakarta_Sans({
	subsets: ["latin"],
	weight: ["200", "300", "400", "500", "600", "700", "800"],
	style: ["normal", "italic"],
	variable: "--font-plus-jakarta",
	display: "swap",
});

const patrickHand = Patrick_Hand_SC({
	subsets: ["latin"],
	weight: ["400"],
	variable: "--font-patrick-hand",
	display: "swap",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body
				className={twMerge(
					"min-h-screen dark:bg-zinc-800 bg-zinc-100 transition-all",
					plusJakarta.variable,
					patrickHand.variable,
				)}
			>
				<ClientProvider>
					<Header />
					{children}
				</ClientProvider>
			</body>
		</html>
	);
}
