FROM node:19 AS base


FROM base AS dependencies

WORKDIR /app
COPY package.json yarn.lock ./
RUN yarn --frozen-lockfile

FROM base AS build

WORKDIR /app
COPY . .
COPY --from=dependencies /app/node_modules ./node_modules
RUN yarn dev-build

FROM node:19 AS deploy
WORKDIR /app
COPY --from=build /app/dist ./
RUN yarn global add http-server
CMD ["http-server", "-c-1", "-p", "5175"]
EXPOSE 5175
