FROM oven/bun:1.0.26-slim as base

FROM base AS build

WORKDIR /app
COPY package.json bun.lockb ./

ENV NODE_ENV=production

RUN bun install --frozen-lockfile
COPY . .
RUN bun run build-prod

FROM oven/bun:1.0.26-slim AS deploy
WORKDIR /app

COPY package.json .
COPY --from=build /app/dist /app


CMD ["bun", "run", "start"]