FROM oven/bun:1.0.14 as base

FROM base AS build

WORKDIR /app
COPY package.json bun.lockb ./

ENV VITE_APP_API_URL="https://api.dev.grail.moe/api/v1/"
ENV VITE_APP_AWS_S3_BUCKET_URL="https://dev.document.grail.moe"
ENV VITE_APP_GOOGLE_ANALYTICS_ID=G-7H1BG8E209

RUN bun install --frozen-lockfile
COPY . .
RUN bun run build

FROM caddy:2.6.2-alpine AS deploy
EXPOSE 443
COPY --from=build /app/dist /usr/share/caddy/holy-grail-dev/
