name: Codecov

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Copy .env_example to .env
        run: cp .env_example .env

      - name: Get the branch name
        id: get_branch
        run: echo "::set-output name=BRANCH_NAME::$(echo ${GITHUB_REF#refs/heads/})"

      - name: Build Docker image (dev branch)
        run: make build version="dev"
        if: steps.get_branch.outputs.BRANCH_NAME == 'dev'

      - name: Build Docker image (master branch)
        run: make build version="prod"
        if: steps.get_branch.outputs.BRANCH_NAME == 'master'

      - name: Run tests with coverage
        run: make coverage version="dev"
        if: steps.get_branch.outputs.BRANCH_NAME == 'dev'

      - name: Run tests with coverage
        run: make coverage version="prod"
        if: steps.get_branch.outputs.BRANCH_NAME == 'master'

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true
