name: Deploy

on:
  workflow_run:
    workflows:
      - "Frontend build"
      - "Backend build"
    branches:
      - master
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/holy-grail

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.MASTER_REMOTE_HOST }}
          username: ${{ secrets.MASTER_REMOTE_USER }}
          key: ${{ secrets.MASTER_SSH_PRIVATE_KEY }}
          script: |
            cd ./holy-grail
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d
            make migrate version=prod
            fi
