name: Deploy

on:
  workflow_run:
    workflows:
      - "Frontend build"
      - "Backend build"
    branches:
      - dev
    types:
      - completed

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/holy-grail

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DEV_REMOTE_HOST }}
          username: ${{ secrets.DEV_REMOTE_USER }}
          key: ${{ secrets.DEV_SSH_PRIVATE_KEY }}
          script: |
            cd ./holy-grail
            docker compose pull
            docker compose up -d
            make migrate
            rm -r ../api-gateway/holy-grail-dev
            docker cp holy-grail-frontend:/usr/share/caddy/holy-grail-dev ../api-gateway/holy-grail-dev/
            docker compose stop holy-grail-frontend
            docker restart api-gateway
