name: CI/CD Pipeline

on:
  push:
    branches:
      - dev
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/holy-grail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run tests with coverage
        run: make coverage version="dev"

      - name: Generate xml
        run: make generate_xml version="dev"

      - name: Override Coverage Source Path for Sonar
        run: |
          pytest_coverage_xml_file_name="holy-grail-backend/backend/coverage.xml"
          echo "GITHUB_WORKSPACE=$GITHUB_WORKSPACE"
          echo 'coverage.xml before:'
          head $GITHUB_WORKSPACE/$pytest_coverage_xml_file_name
          sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' $GITHUB_WORKSPACE/$pytest_coverage_xml_file_name
          echo 'coverage.xml after:'
          head $GITHUB_WORKSPACE/$pytest_coverage_xml_file_name

      - name: SonarQube Scan
        uses: sonarsource/sonarqube-scan-action@master
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CICD_TOKEN }}

      - name: Define tag suffix and Dockerfile
        run: |
          if [[ "${{ github.ref }}" == 'refs/heads/master' ]]; then
            echo "TAG_SUFFIX=" >> $GITHUB_ENV
            echo "DOCKERFILE=Dockerfile.prod" >> $GITHUB_ENV
          else
            echo "TAG_SUFFIX=-dev" >> $GITHUB_ENV
            echo "DOCKERFILE=Dockerfile.dev" >> $GITHUB_ENV
          fi

      - name: Build and push Backend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./holy-grail-backend/backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/holy-grail-backend${{ env.TAG_SUFFIX }}:latest

      - name: Build and push Frontend Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./holy-grail-frontend
          file: ./holy-grail-frontend/${{ env.DOCKERFILE }}
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/holy-grail-frontend${{ env.TAG_SUFFIX }}:latest

      - name: Build and push Scheduler Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./holy-grail-backend/backend
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/holy-grail-scheduler${{ env.TAG_SUFFIX }}:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Print github.ref
        run: echo "github.ref=${{ github.ref }}"

      - name: executing remote ssh commands using private key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_REMOTE_HOST || secrets.MASTER_REMOTE_HOST }}
          username: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_REMOTE_USER || secrets.MASTER_REMOTE_USER }}
          key: ${{ github.ref == 'refs/heads/dev' && secrets.DEV_SSH_PRIVATE_KEY || secrets.MASTER_SSH_PRIVATE_KEY }}
          script: |
            cd ./holy-grail
            if [[ "${{ github.ref }}" == 'refs/heads/master' ]]; then
              docker compose -f docker-compose.prod.yml pull
              docker compose -f docker-compose.prod.yml up -d
              make migrate version=prod
            else
              docker compose pull
              docker compose up -d
              make migrate
              rm -r ../caddy-server/holy-grail-dev
              docker cp holy-grail-frontend:/usr/share/caddy/holy-grail-dev ../caddy-server/holy-grail-dev/
              docker compose stop holy-grail-frontend
              docker restart caddy
            fi
