name: Test

on:
  push:
    branches:
      - dev
      - master
  pull_request:
    branches:
      - dev
      - master

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: vichannnnn/holy-grail

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Copy .env.example to .env
        run: cp .env.example .env

      - name: Run tests with coverage
        run: make coverage version="dev"

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          verbose: true

  check:
    if: always()
    needs: [ Test, Build, Deploy ]
    runs-on: ubuntu-latest
    steps:
      - name: All jobs result
        uses: re-actors/alls-green@release/v1.2.2
        with:
          jobs: ${{ toJSON(needs) }}
